server:
  port: 7004
  

spring:
  application:
    name: New-Order-Service
    
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

 
management:
  endpoints:
    web:
      exposure:
        include: "*"